### ISSUE TITLE
Support providing a custom root

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/hhvm-autoload#10]
We tend to run composer from outside of our VMs, while run HHVM from inside. This means that the paths don't match so the autoloader can't find any of the files.

Being able to specific the root would solve this.

**Comment by fredemmott** [comment]
Would making them relative to the directory containing hh_autoload.json work? e.g. assuming the autoloader stays at vendor/hh_autoload.php, __DIR__.'/../' would be prepended at runtime

**Comment by simonwelsh** [comment]
Yup, that'll also work

**Comment by simonwelsh** [comment]
`testImportTree` doesn't keep the autoloader in `vendor`, so going to need a flag for whether to use the relative path or the provided.
