### ISSUE TITLE
Fact parsing of composer autoload files not recursive

### ISSUE THREAD

**Issue by HRMsimon** [hhvm/hhvm-autoload#13]
There's a couple of packages that have composer autoload a single file, which then goes and loads in a different one with all the function definitions. This stops the default handling of `files` autoload values from working for these packages.

Example: guzzlehttp/guzzle ([composer.json](https://github.com/guzzle/guzzle/blob/dfd01d60a38cf7e16b3456d4b1d7c10033b929c0/composer.json#L26), [referenced file](https://github.com/guzzle/guzzle/blob/dfd01d60a38cf7e16b3456d4b1d7c10033b929c0/src/functions_include.php))

**Comment by fredemmott** [comment]
Is setting `autoloadFilesBehavior` to `exec` a workable approach for you? I'm leaning towards this being a wontfix.

**Comment by HRMsimon** [comment]
#14 prevents that from working for us at the moment, but that's basically what we've done (put the specific files in `extraFiles`).

It's a pity `fact_parse` doesn't divulge if the file has any `require`/`include` statements in it, so you couldn't just add the necessary files as explicit `require`s

**Comment by fredemmott** [comment]
I was thinking of doing a token_get_all() and just looking for T_REQUIRE and friends, but I'm not convinced that is safe without basically adding it to definition-finder, and I'd rather not make that a hard dependency again.

wontfixing as #14 should make this unneeded.
