### ISSUE TITLE
Class undefined error whenever a class is a child of an abstract class

### ISSUE THREAD

**Issue by imperio59** [hhvm/hhvm-autoload#8]
I have setup hhvm-autoload in my project.

I have an index.php file to route web requests to the right controller. index.php does `require_once(__DIR__.'/vendor/hh_autoload.php');`

I have two controller classes: `Foo` and `Bar`.

`Foo` does not extend any other class and has a single static method `bar()` which returns a string.

`Bar` extends `BaseController` and overrides some methods. `BaseController` is defined as abstract.

index.php can call `Foo:bar()` with no issue, however when hhvm hits the line with the `Bar` class, it throws a Class Undefined error.

I checked and `Bar` is properly listed in the generated hh_autoload.php file.

Neither Foo, Bar or BaseController are in a namespace. The project also includes XHP and a few other libs via composer.

Any idea what could be causing this?

If I comment out the `extends BaseController` statement from the `Bar` definition, it loads the class properly and runs it fine.

HHVM data:
HipHop VM 3.18.3 (rel)
Compiler: tags/HHVM-3.18.3-0-g1ddd4af7b1342c20635afbdc67701fbcbdf97bfa
Repo schema: 61b13efcfd4e2fabea72495f96208746a568a688

I should also add that hh_client returns no errors.

**Comment by fredemmott** [comment]
- Is BaseController in your hh_autoload.php?
 - What version?
 - Does changing the parser option help? (either 'definition-finder', or 'ext-factparse', default depends on your version of hhvm-autoload)

**Comment by fredemmott** [comment]
Also, a true code sample would be useful.

**Comment by imperio59** [comment]
I'm trying to repro this with a new set of dummy classes. So far it's not reproing, so I'm not really sure wtf is going on. Will provide a code sample once I get a more clean repro...

**Comment by fredemmott** [comment]
In addition to the previous questions, does `hhvm -l` return anything on the file containing BaseController?

**Comment by fredemmott** [comment]
it's most likely either failing to parse with whichever parser you're using, or require() is failing on that file for some other reason.

If you're using the most recent version of hhvm-autoload on 3.18, you should be using ext-factparse by default, which uses HHVM's own parser - so that would likely indicate something wrong with the contents of the file. If you're using definition-finder, I've likely missed something, and a repro over at https://github.com/hhvm/definition-finder/issues would be useful.

**Comment by fredemmott** [comment]
You can also try:

```
$ hhvm -m debug
hphpd> require_once('vendor/hh_autoload.php')
hphpd> new BaseController()
```

If everything's working correctly, that should show an error about not being able to create instances of abstract classes.

**Comment by imperio59** [comment]
I think this was human error. It seems I had an interface file with a syntax error, somehow hh_client wasn't picking this up. When I fixed this the error went away. My bad :(
