### ISSUE TITLE
PSR filters don't like paths without an ending /

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/hhvm-autoload#9]
PSR0Filter and PSR4Filter have issues when a psr autoload declaration doesn't end with a `/` (e.g. php-resque's)

My fix for this is to add:
```
    $this->root = rtrim($this->root, '/').'/';
```

to the `BasePSRFilter` constructor.

**Comment by fredemmott** [comment]
Any chance you've got time for a PR (with tests) for this and the other one? I'm unlikely to get to this before 3.21 due to non-HHVM work + Defcon/blackhat.
